// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgaaIITG2jz5d0Zk15j28p7iGmo0npXk8',
    appId: '1:254099584755:web:f253f7574c6762c97ae986',
    messagingSenderId: '254099584755',
    projectId: 'contact-app-bf60a',
    authDomain: 'contact-app-bf60a.firebaseapp.com',
    storageBucket: 'contact-app-bf60a.firebasestorage.app',
    measurementId: 'G-JJ80FHLHKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACpnDFA5LYJ_DQ1sl5_b5NXTE0g9Qw4RE',
    appId: '1:254099584755:android:e002e78465d3c6b77ae986',
    messagingSenderId: '254099584755',
    projectId: 'contact-app-bf60a',
    storageBucket: 'contact-app-bf60a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFosRsm8VTkXtuoqqJKrUq9rk-pyAGrLY',
    appId: '1:254099584755:ios:d869ee6414979e407ae986',
    messagingSenderId: '254099584755',
    projectId: 'contact-app-bf60a',
    storageBucket: 'contact-app-bf60a.firebasestorage.app',
    iosBundleId: 'com.example.hotuanphuoc2224802010872Lab4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFosRsm8VTkXtuoqqJKrUq9rk-pyAGrLY',
    appId: '1:254099584755:ios:d869ee6414979e407ae986',
    messagingSenderId: '254099584755',
    projectId: 'contact-app-bf60a',
    storageBucket: 'contact-app-bf60a.firebasestorage.app',
    iosBundleId: 'com.example.hotuanphuoc2224802010872Lab4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgaaIITG2jz5d0Zk15j28p7iGmo0npXk8',
    appId: '1:254099584755:web:87f870d16f21d1917ae986',
    messagingSenderId: '254099584755',
    projectId: 'contact-app-bf60a',
    authDomain: 'contact-app-bf60a.firebaseapp.com',
    storageBucket: 'contact-app-bf60a.firebasestorage.app',
    measurementId: 'G-7YQCL26Q8J',
  );
}
